In [14]:
import numpy as np

from configs.logistic_regression_config import cfg
from models.logistic_regression_model import LogReg
from models.logistic_regression_model import LogRegWeightsInitType
from models.logistic_regression_model import LogRegStoppingCriteria

#from models.LogReg import LogReg
from ft_datasets.digits_dataset import Digits
from ft_datasets.base_dataset_classes import PreprocessType
from utils.visualisation import Visualisation
from utils import metrics


In [5]:
cfg

{'project_name': 'DigitsLogReg',
 'train_set_percent': 0.8,
 'valid_set_percent': 0.1,
 'data_preprocess_type': <DataProcessTypes.standardization: 1>,
 'weights_init_type': <WeightsInitType.normal: 1>,
 'weights_init_kwargs': {'sigma': 1},
 'gamma': 0.01,
 'reg_coefficient': 0.01,
 'gd_stopping_criteria': <GDStoppingCriteria.epoch: 1>,
 'nb_epoch': 12,
 'gradient_norm_threshold': 3,
 'difference_norm_threshold': 0.02,
 'nb_repeats': 20,
 'batch_size': 32,
 'visualize': True}

In [8]:
digits = Digits(cfg)

model = LogReg(cfg, digits.k, digits.d,
               logging=False,
               env_path='../../env.env'
               )

In [9]:


print('---------------------------- TRAIN ----------------------------')
model.train(digits.inputs_train, digits.targets_train, digits.inputs_valid, digits.targets_valid)




---------------------------- TRAIN ----------------------------
gradient_descent_epoch
epoch = 0
Target function value on train set: 3412.780191290768
Confusion matrix on train set:
[[ 30.  65.   6.   1.   2.  26.   4.   0.   3.   0.]
 [  0.   4.  35.  18.  13.  40.   1.   1.  10.  26.]
 [  0.   0.   4.  76.   4.  38.   4.   2.   2.   8.]
 [  1.   2.   1.  12.  13.  93.  13.   4.   0.   2.]
 [  2.   0. 116.   1.   8.   0.   0.  13.   5.   3.]
 [ 31.  18.  14.  19.   1.   6.  49.   2.   1.   1.]
 [  1.   3.  95.   0.   2.   1.   3.   1.  37.   2.]
 [  8.   2.  19.  12.  73.   3.   5.  26.   3.   7.]
 [  0.   4.   6.  51.   1.  20.   2.  15.   5.  30.]
 [  9.   0.   3.  13.   0.  43.  35.  34.   2.   7.]]
Accuracy on train set: 0.07306889352818371
Confusion matrix on validation set:
[[ 4.  9.  0.  0.  0.  2.  3.  0.  0.  1.]
 [ 0.  0.  5.  1.  6.  6.  0.  0.  2.  2.]
 [ 0.  0.  0. 16.  1.  4.  0.  0.  0.  0.]
 [ 0.  1.  0.  2.  2.  9.  3.  0.  0.  0.]
 [ 0.  0. 16.  0.  0.  0.  0.  1.  0

In [10]:
model.save("./checkpoints/1.pickle")

In [11]:
logreg = LogReg.load("./checkpoints/1.pickle")

In [15]:
pred = logreg( digits.inputs_valid)

confusion_matrix = metrics.confusion_matrix(pred, digits.targets_valid)
accuracy = metrics.accuracy_mat(confusion_matrix)
print(accuracy)

0.9162011173184358
